# Generated by Django 5.2.6 on 2025-09-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('place_type', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('rating', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
