# Generated by Django 5.2.6 on 2025-09-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='photo_filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
