# Generated by Django 5.2.6 on 2025-09-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_photo_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='photo',
        ),
    ]
