# Generated by Django 5.2.6 on 2025-09-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_place_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
