# Generated by Django 5.2.6 on 2025-09-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='photo_filename',
        ),
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
