# Generated by Django 5.2.6 on 2025-09-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_remove_place_photo_filename_alter_place_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='photo_filename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
